export const OFFERS_DUMMY_DATA = [
  {
    id: "001",
    offerType: "BUS",
    title: "Save up to Rs 500 on bus tickets",
    validity: "Valid till 31 April",
    couponCode: "BUS500",
    backgroundImage: "offers/offer1.png",
  },
  {
    id: "002",
    offerType: "BUS",
    title: "Save up to Rs 500 on IDFC FIRST Bank Credit cards",
    validity: "Valid till 31 May",
    couponCode: "IDFC500",
    backgroundImage: "offers/offer1.png",
  },
  {
    id: "003",
    offerType: "BUS",
    title: "Save up to 500 with HDFC Bank credit cards",
    validity: "Valid till 31 Oct",
    couponCode: "HDFC500",
    backgroundImage: "offers/offer1.png",
  },
  {
    id: "004",
    offerType: "BUS",
    title: "Save up to Rs. 500 with ICICI Bank Net Banking",
    validity: "Valid till 31 Dec",
    couponCode: "ICICINB500",
    backgroundImage: "offers/offer1.png",
  },
  {
    id: "005",
    offerType: "TRAIN",
    title: "Get Rs 120 off on train tickets",
    validity: "Valid till 31 Dec",
    couponCode: "SUMMERNEW",
    backgroundImage: "offers/offer2.avif",
  },
  {
    id: "006",
    offerType: "TRAIN",
    title: "Get 50% off upto Rs.300 on Alternate Trip Premium",
    validity: "Valid till 31 Dec",
    couponCode: "HALFPRICE",
    backgroundImage: "offers/offer2.avif",
  },
  {
    id: "007",
    offerType: "TRAIN",
    title: "Get Rs 150 off on train tickets",
    validity: "Valid till 31 Dec",
    couponCode: "CHARDHAM",
    backgroundImage: "offers/offer2.avif",
  },
  {
    id: "008",
    offerType: "TRAIN",
    title: "Get upto Rs.100 off on train tickets",
    validity: "Valid till 31 Dec",
    couponCode: "STARTRAIL",
    backgroundImage: "offers/offer2.avif",
  },
];

export const WHATS_NEW_DUMMY = [
  { id: "001", backgroundImage: "whatsNew/1.webp" },
  { id: "002", backgroundImage: "whatsNew/2.webp" },
  { id: "003", backgroundImage: "whatsNew/3.webp" },
  { id: "004", backgroundImage: "whatsNew/4.webp" },
  { id: "005", backgroundImage: "whatsNew/5.webp" },
  { id: "006", backgroundImage: "whatsNew/6.webp" },
  { id: "007", backgroundImage: "whatsNew/7.webp" },
  { id: "008", backgroundImage: "whatsNew/8.webp" },
];

export const OFFERS_PAGE_DUMMY = [
  {
    id: "001",
    backgroundImage: "offerPage/1.png",
    title: "Save up to Rs. 300 in AP, Telangana routes",
    couponCode: "SUPERHIT",
  },
  {
    id: "002",
    backgroundImage: "offerPage/2.png",
    title: "Save up to Rs 300 on Karnataka,Tamil Nadu, Kerala routes",
    couponCode: "CASH300",
  },
  {
    id: "003",
    backgroundImage: "offerPage/3.png",
    title: "Save up to Rs 500 on IDFC FIRST Bank Credit cards",
    couponCode: "IDFC500",
  },
  {
    id: "004",
    backgroundImage: "offerPage/4.png",
    title: "Save up to 500 with HDFC Bank credit cards",
    couponCode: "HDFC500",
  },
  {
    id: "005",
    backgroundImage: "offerPage/5.png",
    title: "Save up to Rs. 500 with ICICI Bank Net Banking",
    couponCode: "ICICINB500",
  },
  {
    id: "006",
    backgroundImage: "offerPage/6.png",
    title: "Save upto Rs 200 with AU Bank Credit Cards",
    couponCode: "AUBUS200",
  },
  {
    id: "007",
    backgroundImage: "offerPage/7.png",
    title: "Save up to Rs 200 on Primo operators.",
    couponCode: "PRIMODAY",
  },
  {
    id: "008",
    backgroundImage: "offerPage/8.png",
    title: "Save up to Rs 500 on bus tickets",
    couponCode: "RED500",
  },
  {
    id: "009",
    backgroundImage: "offerPage/9.png",
    title: "Enjoy 10% off on Karnataka routes.",
    couponCode: "NAMMA101",
  },
  {
    id: "010",
    backgroundImage: "offerPage/10.png",
    title: "Save up to Rs 300 on Chartered Bus",
    couponCode: "CHARTED15",
  },
];

export const BUS_RESULTS = [
  {
    id: "B001",
    companyName: "PTC-SkyBus",
    busModel: "Bharat Benz",
    isAc: true,
    isSeater: true,
    isSleeper: true,
    isDirect: true,
    rating: 4.8,
    totalNoOfRatings: 630,
    departureTime: "23:15",
    arrivalTime: "07:30",
    duration: "8h 15m",
    price: 529,
    noOfSingleSeatsFree: 5,
    noOfSleepersFree: 25,
    tags: ["New Bus", "On Time", "Highly rated by women"],
  },
  {
    id: "B002",
    companyName: "Zingbus",
    busModel: "Volvo B11R",
    isAc: true,
    isSeater: false,
    isSleeper: true,
    isDirect: true,
    rating: 4.5,
    totalNoOfRatings: 420,
    departureTime: "21:00",
    arrivalTime: "05:30",
    duration: "8h 30m",
    price: 750,
    noOfSingleSeatsFree: 2,
    noOfSleepersFree: 15,
    tags: ["Water Bottle", "Blanket", "Live Tracking"],
  },
  {
    id: "B003",
    companyName: "VRL Travels",
    busModel: "Scania Multi-Axle",
    isAc: true,
    isSeater: true,
    isSleeper: false,
    isDirect: false,
    rating: 4.2,
    totalNoOfRatings: 850,
    departureTime: "18:45",
    arrivalTime: "03:15",
    duration: "8h 30m",
    price: 450,
    noOfSingleSeatsFree: 10,
    noOfSleepersFree: 0,
    tags: ["Experienced Driver", "Clean", "CCTV"],
  },
  {
    id: "B004",
    companyName: "IntrCity SmartBus",
    busModel: "Volvo",
    isAc: true,
    isSeater: true,
    isSleeper: true,
    isDirect: true,
    rating: 4.6,
    totalNoOfRatings: 1200,
    departureTime: "22:30",
    arrivalTime: "06:45",
    duration: "8h 15m",
    price: 899,
    noOfSingleSeatsFree: 4,
    noOfSleepersFree: 20,
    tags: ["Toilet", "Lounge Access", "WIFI"],
  },
  {
    id: "B005",
    companyName: "SRS Travels",
    busModel: "Ashok Leyland",
    isAc: false,
    isSeater: true,
    isSleeper: true,
    isDirect: true,
    rating: 3.8,
    totalNoOfRatings: 310,
    departureTime: "20:00",
    arrivalTime: "04:30",
    duration: "8h 30m",
    price: 350,
    noOfSingleSeatsFree: 8,
    noOfSleepersFree: 12,
    tags: ["Budget", "Multiple Stops"],
  },
  {
    id: "B006",
    companyName: "Orange Travels",
    busModel: "Volvo Multi-Axle",
    isAc: true,
    isSeater: false,
    isSleeper: true,
    isDirect: true,
    rating: 4.7,
    totalNoOfRatings: 540,
    departureTime: "23:55",
    arrivalTime: "08:15",
    duration: "8h 20m",
    price: 1100,
    noOfSingleSeatsFree: 1,
    noOfSleepersFree: 18,
    tags: ["Pillow", "Reading Light", "USB Port"],
  },
  {
    id: "B007",
    companyName: "Neeta Travels",
    busModel: "Mercedes-Benz",
    isAc: true,
    isSeater: true,
    isSleeper: false,
    isDirect: true,
    rating: 4.0,
    totalNoOfRatings: 670,
    departureTime: "16:30",
    arrivalTime: "00:45",
    duration: "8h 15m",
    price: 600,
    noOfSingleSeatsFree: 15,
    noOfSleepersFree: 0,
    tags: ["Express", "Movie"],
  },
  {
    id: "B008",
    companyName: "Mahasagar Travels",
    busModel: "Bharat Benz AC",
    isAc: true,
    isSeater: true,
    isSleeper: true,
    isDirect: false,
    rating: 3.5,
    totalNoOfRatings: 220,
    departureTime: "19:15",
    arrivalTime: "04:00",
    duration: "8h 45m",
    price: 499,
    noOfSingleSeatsFree: 6,
    noOfSleepersFree: 10,
    tags: ["Reliable", "Emergency Contact"],
  },
  {
    id: "B009",
    companyName: "Kallada Travels",
    busModel: "Scania",
    isAc: true,
    isSeater: true,
    isSleeper: true,
    isDirect: true,
    rating: 4.3,
    totalNoOfRatings: 480,
    departureTime: "22:00",
    arrivalTime: "06:15",
    duration: "8h 15m",
    price: 850,
    noOfSingleSeatsFree: 3,
    noOfSleepersFree: 22,
    tags: ["GPS", "Premium", "Water"],
  },
  {
    id: "B010",
    companyName: "Greenline Travels",
    busModel: "Volvo Hybrid",
    isAc: true,
    isSeater: true,
    isSleeper: false,
    isDirect: true,
    rating: 4.4,
    totalNoOfRatings: 390,
    departureTime: "15:00",
    arrivalTime: "23:30",
    duration: "8h 30m",
    price: 650,
    noOfSingleSeatsFree: 12,
    noOfSleepersFree: 0,
    tags: ["Eco-friendly", "Spacious", "Snacks"],
  },
];

export const TRAIN_RESULTS = [
  {
    id: "T001",
    companyName: "Rajdhani Express",
    busModel: "Superfast AC",
    isAc: true,
    isSeater: true,
    isSleeper: true,
    isDirect: true,
    rating: 4.9,
    totalNoOfRatings: 2500,
    departureTime: "16:00",
    arrivalTime: "22:00",
    duration: "6h 00m",
    price: 1200,
    noOfSingleSeatsFree: 50,
    noOfSleepersFree: 120,
    tags: ["Food Included", "On Time", "Clean"],
  },
  {
    id: "T002",
    companyName: "Shatabdi Express",
    busModel: "Chair Car AC",
    isAc: true,
    isSeater: true,
    isSleeper: false,
    isDirect: true,
    rating: 4.7,
    totalNoOfRatings: 1800,
    departureTime: "06:15",
    arrivalTime: "12:45",
    duration: "6h 30m",
    price: 950,
    noOfSingleSeatsFree: 80,
    noOfSleepersFree: 0,
    tags: ["Fast", "Breakfast", "New Coaches"],
  },
  {
    id: "T003",
    companyName: "Duronto Express",
    busModel: "Non-stop AC",
    isAc: true,
    isSeater: false,
    isSleeper: true,
    isDirect: true,
    rating: 4.6,
    totalNoOfRatings: 1100,
    departureTime: "20:30",
    arrivalTime: "03:00",
    duration: "6h 30m",
    price: 1100,
    noOfSingleSeatsFree: 0,
    noOfSleepersFree: 90,
    tags: ["No Halts", "Priority", "Quiet"],
  },
  {
    id: "T004",
    companyName: "Garib Rath",
    busModel: "Economy AC",
    isAc: true,
    isSeater: false,
    isSleeper: true,
    isDirect: false,
    rating: 4.0,
    totalNoOfRatings: 900,
    departureTime: "21:45",
    arrivalTime: "05:15",
    duration: "7h 30m",
    price: 600,
    noOfSingleSeatsFree: 0,
    noOfSleepersFree: 45,
    tags: ["Pocket Friendly", "Bedding Provided"],
  },
  {
    id: "T005",
    companyName: "Sampark Kranti",
    busModel: "Superfast Express",
    isAc: false,
    isSeater: true,
    isSleeper: true,
    isDirect: false,
    rating: 4.2,
    totalNoOfRatings: 1300,
    departureTime: "14:20",
    arrivalTime: "22:50",
    duration: "8h 30m",
    price: 450,
    noOfSingleSeatsFree: 100,
    noOfSleepersFree: 200,
    tags: ["Budget", "Good Connectivity"],
  },
  {
    id: "T006",
    companyName: "Tejas Express",
    busModel: "Corporate AC",
    isAc: true,
    isSeater: true,
    isSleeper: false,
    isDirect: true,
    rating: 4.8,
    totalNoOfRatings: 750,
    departureTime: "08:30",
    arrivalTime: "15:00",
    duration: "6h 30m",
    price: 1500,
    noOfSingleSeatsFree: 40,
    noOfSleepersFree: 0,
    tags: ["Infotainment", "Premium Food", "CCTV"],
  },
  {
    id: "T007",
    companyName: "Humsafar Express",
    busModel: "Premium 3AC",
    isAc: true,
    isSeater: false,
    isSleeper: true,
    isDirect: true,
    rating: 4.4,
    totalNoOfRatings: 600,
    departureTime: "22:15",
    arrivalTime: "06:45",
    duration: "8h 30m",
    price: 1050,
    noOfSingleSeatsFree: 0,
    noOfSleepersFree: 75,
    tags: ["Modern", "Mobile Charging", "GPS"],
  },
  {
    id: "T008",
    companyName: "Gatiman Express",
    busModel: "High Speed AC",
    isAc: true,
    isSeater: true,
    isSleeper: false,
    isDirect: true,
    rating: 4.9,
    totalNoOfRatings: 400,
    departureTime: "08:10",
    arrivalTime: "09:50",
    duration: "1h 40m",
    price: 800,
    noOfSingleSeatsFree: 60,
    noOfSleepersFree: 0,
    tags: ["Fastest in India", "Hostesses", "Wifi"],
  },
  {
    id: "T009",
    companyName: "Vande Bharat",
    busModel: "Next Gen AC",
    isAc: true,
    isSeater: true,
    isSleeper: false,
    isDirect: true,
    rating: 4.9,
    totalNoOfRatings: 1500,
    departureTime: "06:00",
    arrivalTime: "14:00",
    duration: "8h 00m",
    price: 1600,
    noOfSingleSeatsFree: 120,
    noOfSleepersFree: 0,
    tags: ["Made in India", "Rotating Seats", "Auto Doors"],
  },
  {
    id: "T010",
    companyName: "Jan Shatabdi",
    busModel: "Intercity Express",
    isAc: false,
    isSeater: true,
    isSleeper: false,
    isDirect: false,
    rating: 3.9,
    totalNoOfRatings: 2100,
    departureTime: "12:00",
    arrivalTime: "19:30",
    duration: "7h 30m",
    price: 300,
    noOfSingleSeatsFree: 150,
    noOfSleepersFree: 0,
    tags: ["Frequent", "Affordable", "Daily"],
  },
];
